UltraFerous/finalProjectLHL

- .env
- .gitignore
- package-lock.json
- package.json
- server/db/connection.js
- server/index.js
- server/package-lock.json
- server/package.json
- Connect Node to database in connection.js
- Install morgan, dotenv, and body-parser packages and require them in index.js
- Install nodemon
> Connect Express to PostgreSQL Database

- server/db/queries/developers.js
- server/db/queries/orgs-api.js
- server/db/queries/orgs.js
- server/db/queries/projects-api.js
- server/db/queries/projects.js
- server/db/queries/users-api.js
- server/db/queries/users.js
- server/index.js
- server/routes/developers.js
- server/routes/orgs-api.js
- server/routes/orgs.js
- server/routes/projects-api.js
- server/routes/projects.js
- server/routes/users-api.js
- server/routes/users.js
- Create all route files in routes directory
- Create all query helper files in queries directory
- Import routes in Express index.js
- Define route middleware in Express server
- Create routes subdirectory in server directory
- Create queries subdirectory in db directory
> Define Routes in Express Server

- server/db/queries/developers.js
- server/db/queries/orgs-api.js
- server/db/queries/orgs.js
- server/db/queries/projects-api.js
- server/db/queries/projects.js
- server/db/queries/users-api.js
- server/db/queries/users.js
Added queries to search for users, projects, tags and organizations.
> Added multiple database queries

- client/package-lock.json
- client/package.json
- client/src/assets/styles/theme.js
- client/src/main.jsx
- Create theme.js file
- Apply custom theme in main.js
- Wrapp App component in ThemeProvider component to give all child components access to custom theme
> Install Material UI

- server/db/queries/developers.js
- server/db/queries/orgs-api.js
- server/db/queries/orgs.js
- server/db/queries/projects-api.js
- server/db/queries/projects.js
- server/db/queries/users-api.js
Added queries for modification and project tags/contributions.
Added additional information to some queries.
> Added modification and project tags/contributions queries

- server/db/queries/orgs.js
- server/db/queries/projects.js
> fixed a name issue in projectDataSearchID

- client/src/pages/Project.jsx
- server/routes/projects.js
-Added conditional rendering of project edit link if user is the project admin
-Added conditional rendering of apply to project link if a user is logged in
Having same issue as yesterday where server response appears not to be coming through. Pushing branch and restarting computer before trying to fix more.
> updated conditional rendering of project edit link

- client/src/context/UserContext.jsx
- client/src/pages/Project.jsx
- client/src/pages/ProjectApplication.jsx
- server/routes/projects.js
- server/routes/users-api.js
-Updated project application page to include form & submission logic
- Not able to fix issue with user state from context API persisting across pages. Will get mentor help later. Pushing existing code to update code base for now.
> Client/project details/conditional rendering

- client/package.json
- client/src/pages/CreateOrg.jsx
I only updated the createOrg since I don't know what else is being worked on.
> Added proxy to the client

- client/src/pages/DeveloperList.jsx
- client/src/pages/Home.jsx
- server/index.js
- server/routes/developers.js
- server/routes/projects.js
- completed code for developer list route & react page template. No styling. Still need search results data. Just used list of all developers for now.
> Developer list

- client/src/App.jsx
- client/src/context/UserContext.jsx
- client/src/main.jsx
- client/src/pages/LogInUser.jsx
- client/src/pages/Project.jsx
- client/src/pages/ProjectApplication.jsx
- client/src/pages/RegisterUser.jsx
- server/routes/users.js
-attempted to fix user state persisting issue, didn't work but keeping a few of the changes.
> made a few changes to the UserContext and ContextProvider

- client/src/App.jsx
- client/src/components/TempLinks.jsx
- client/src/pages/Project.jsx
- server/routes/orgs.js
Add temporary links component to each page for use during development
> add temporary links component for development purposes

- client/src/App.jsx
- client/src/components/NavBar.jsx
- client/src/context/UserContext.jsx
- server/routes/users-api.js
- Add code to store user data in local storage when user logs in and use that to update user state when page is refreshed. Log out removes user data from local storage.
> Context api/update user state with cookies

- client/src/components/Card.jsx
- client/src/components/DeveloperCardList.jsx
- client/src/components/ProjectCardList.jsx
Added bootstrap styling to card and cardlist
> add bootstrap styling to card and cardlist

- client/src/components/BrowseTags.jsx
- client/src/components/DeveloperCardList.jsx
- client/src/components/ProjectCardList.jsx
- client/src/components/SearchBar.jsx
- client/src/components/SearchContainer.jsx
- client/src/pages/DeveloperList.jsx
- client/src/pages/Home.jsx
- client/src/pages/LogInUser.jsx
- client/src/pages/ProjectList.jsx
- server/routes/users-api.js
Updated home page & log in page styling
Updated route for user data to include org id
> User functions update parameters

- client/src/components/NavBar.jsx
Added conditional rendering to the navbar links and buttons depending on whether or not a user is logged in
> added conditional rendering to the navbar buttons and links

- client/src/context/UserContext.jsx
- client/src/pages/LogInUser.jsx
- client/src/pages/Project.jsx
Created one click log in buttons for demo accounts. Make it easier to demo and also for testing during development.
Fixed nested user state issue
> fix nested user state issue

- client/src/components/NavBar.jsx
- client/src/pages/CreateProject.jsx
- client/src/pages/EditProject.jsx
- client/src/pages/NotFound.jsx
- client/src/pages/ProjectApplication.jsx
- client/src/pages/RegisterUser.jsx
- client/src/pages/UserProfile.jsx
- server/routes/users.js
Added route and jsx for user details page
Added styling to pages with forms and the not found page
Added dynamic profile link to navbar
> User details route

- client/src/App.jsx
- client/src/components/NavBar.jsx
- client/src/components/OrgCardList.jsx
- client/src/pages/OrgList.jsx
- server/routes/orgs.js
Set up org list page to display all orgs & org search results when we get that functionality working
Added navlink to Organizations
> Org list page

- client/src/components/NavBar.jsx
- client/src/context/UserContext.jsx
- client/src/pages/CreateOrg.jsx
- client/src/pages/Home.jsx
- server/db/queries/orgs-api.js
- server/routes/orgs-api.js
Updated state and local storage to update the user object with organization_id when a new organization is created.
> Add orgid to user state

- client/src/components/OrgCardList.jsx
- client/src/pages/UserProfile.jsx
- server/routes/users.js
Added projects to user details page
> update user profile page to display projects

- client/src/App.jsx
- client/src/components/BrowseTags.jsx
- client/src/components/SearchBar.jsx
- client/src/components/SearchContainer.jsx
- client/src/pages/DeveloperList.jsx
- client/src/pages/ProjectList.jsx
- client/src/styles/App.css
- client/src/styles/App.scss
- server/routes/developers.js
- server/routes/projects.js
- server/routes/users.js
- Conditionally navigate to the correct route from the SearchBar component
- Conditionally render search results or all cards in ProjectList and DeveloperList components
- Implement browse tags functionality
- Move developer search functionality from users route to developers route
- Conditional styling on search type buttons
- Modify btn-primary styles
> Implement Project and User Search and Browse

- server/db/queries/orgs.js
- server/db/queries/projects.js
- server/db/queries/users.js
Added GROUP BY clause to the browse queries.
> Fixed duplicate search bug

- client/src/pages/RegisterUser.jsx
- server/routes/users-api.js
Updated registration form to add developer links to database when form submitted.
Added checkboxes to registration form for developer tags & update route to add tags to database when form submitted.
> Registration page developer fields

- client/src/pages/CreateProject.jsx
- client/src/pages/RegisterUser.jsx
- server/db/queries/projects-api.js
- server/routes/projects-api.js
Added questions to new project page to determine which tags to add to a new project.
Updated route to insert project tags into database.
> New project form tags

- client/src/pages/OrgProfile.jsx
- server/db/queries/orgs.js
Updated db query to include user image in order to display it on the org details page
> add org admin image to org details page

- client/src/components/Card.jsx
- client/src/components/DeveloperCardList.jsx
- client/src/components/OrgCardList.jsx
- client/src/components/ProjectCardList.jsx
- client/src/pages/DeveloperList.jsx
- client/src/pages/Home.jsx
- client/src/pages/OrgList.jsx
- client/src/pages/ProjectList.jsx
- Adjust Row component in ProjectCardList to display three Col components per line
- Adjust Row component in DeveloperCardList to display three Col components per line
- Adjust Row component in OrgCardList to display three Col components per line
- Change max width of Card components to 100% of parent element
- Place everything in a Container component in DeveloperList, ProjectList, and OrgList
- Put all components except for hero in a Container component in Home.jsx
> Fix Layout on Pages with Lists

- client/src/pages/LogInUser.jsx
Fix login credentials for quick login buttons now that seed data has been updated
> update quick login button credentials

- client/src/App.jsx
- client/src/pages/DeveloperList.jsx
- client/src/pages/OrgList.jsx
- client/src/pages/ProjectList.jsx
- Add endpoint variable to useEffect dependency array in ProjectList to ensure component re-renders whenever user navigates to a new route
- Add endpoint variable to useEffect dependency array in DeveloperList to ensure component re-renders whenever user navigates to a new route
- Add endpoint variable to useEffect dependency array in OrgList to ensure component re-renders whenever user navigates to a new route
> Fix Component Rendering Issue

- client/src/context/UserContext.jsx
Fixed bug that broke app.
Need to do more work on DM notifications.
> fix app breaking bug.

- client/src/components/NavBar.jsx
- client/src/context/UserContext.jsx
- client/src/pages/LogInUser.jsx
-DM notifications complete. Just need to make message icon in navbar a link to messages page when it's built
> fix count in message notifications feature

- client/src/App.jsx
- client/src/pages/MessagesList.jsx
- server/db/queries/messages.js
- server/routes/messages-api.js
- server/routes/messages.js
- Create MessagesList component
- Modify allMessageThreads query to include user image and username
- Add messagesList route to App.jsx
> Create MessagesList Page

- client/src/components/NavBar.jsx
Made messages icon in NavBar a link to a user's message list.
> make message notification icon a link to message list

- client/src/App.jsx
- client/src/pages/Messages.jsx
- client/src/pages/MessagesList.jsx
- client/src/styles/App.css
- client/src/styles/App.scss
- server/db/queries/messages.js
- Make GET request to messages/:userId/:otherUserId
- Build Messages component
- Render array of messages
- Render message input element
- Different alignment for current user and other user
- Add auto scroll to bottom on page load and on new message
- Fix bug in fetching messages list
> Create Messages Page

- client/src/pages/DeveloperList.jsx
- client/src/pages/OrgList.jsx
- client/src/pages/Project.jsx
- client/src/pages/ProjectList.jsx
- client/src/pages/QuickDeveloperList.jsx
- client/src/pages/QuickProjectList.jsx
- client/src/pages/UserProfile.jsx
Added loading state to all pages with images
> add loading state to all pages with images

- client/src/App.jsx
- client/src/pages/OrgProfile.jsx
- client/src/pages/UserProfile.jsx
- Add Link to direct message in UserProfile.jsx
- Add Link to direct message in OrgProfile.jsx
- Move /messages route above catch-all route
> Fix All Contact Me Links

- client/src/pages/Messages.jsx
- Call UserContext updateMessageCount method to set new message count to zero when fetching messages
> Reset New Message Count After Fetching Messages
